// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Smraa_AlYaman.Infrastructure.Persistence;

#nullable disable

namespace Smraa_AlYaman.Infrastructure.Migrations
{
    [DbContext(typeof(SmraaAlYamanDbContext))]
    partial class SmraaAlYamanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Smraa_AlYaman.Domain.Availablty.Audits.AvailabltyAudit", b =>
                {
                    b.Property<Guid>("AuditId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRecovered")
                        .HasColumnType("bit");

                    b.HasKey("AuditId");

                    b.ToTable("AvailabltyAudits");
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.Availablty.ProductBranchesAvailability", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("BrancheId")
                        .HasColumnType("int");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductId", "BrancheId");

                    b.HasIndex("BranchId");

                    b.ToTable("Availabilities", t =>
                        {
                            t.HasTrigger("tr_AvailabltyAudit");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.Barcodes.Audits.BarcodeAudit", b =>
                {
                    b.Property<Guid>("AuditId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAllowedOnline")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecovered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("UnitsCountPerPackage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AuditId");

                    b.ToTable("BarcodeAudits");
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.Barcodes.Barcode", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAllowedOnline")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("UnitsCountPerPackage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Code");

                    b.HasIndex("ProductId");

                    b.ToTable("Barcodes", t =>
                        {
                            t.HasTrigger("barcodeaudit");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.Branchs.Audits.BranchAudit", b =>
                {
                    b.Property<Guid>("AuditId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BranchAddress")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("BranchPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecovered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("AuditId");

                    b.ToTable("BranchAudits");
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.Branchs.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchAddress")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("BranchPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Branches", t =>
                        {
                            t.HasTrigger("BranchAudit");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.CatagoryGroupAndBrand.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Brands", (string)null);
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.CatagoryGroupAndBrand.Catagory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Catagories", (string)null);
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.CatagoryGroupAndBrand.CountryOfOrigin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ZCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("CountriesOfOrigin", (string)null);
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.CatagoryGroupAndBrand.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ProductGroups", (string)null);
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.CustomPrices.Audits.CustomPriceAudit", b =>
                {
                    b.Property<Guid>("AuditId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecovered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("LowestPriceForSale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AuditId");

                    b.ToTable("CustomPriceAudits");
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.CustomPrices.CustomPrice", b =>
                {
                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LowestPriceForSale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BranchId", "Code");

                    b.HasIndex("Code");

                    b.ToTable("CustomPrices", t =>
                        {
                            t.HasTrigger("SupplayerAudit");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.OrderItems.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BarcodeNavigationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BarcodeNavigationCode");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.Orderes.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.ProductPrices.Audits.ProductPriceAudit", b =>
                {
                    b.Property<Guid>("AuditId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsNotSellable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecovered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsWaghted")
                        .HasColumnType("bit");

                    b.Property<decimal>("LowestPricePerSmallistUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("PricePerSmallistUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductPriceUnits")
                        .HasColumnType("int");

                    b.Property<decimal>("SmallistUnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionsSammary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("WholesalePricePerSmallistUnit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AuditId");

                    b.ToTable("PriceAudits");
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.ProductPrices.ProductPrice", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsNotSellable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWaghted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LowestPricePerSmallistUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("PricePerSmallistUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductPriceUnits")
                        .HasColumnType("int");

                    b.Property<decimal>("SmallistUnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionsSammary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("WholesalePricePerSmallistUnit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ProductPrices", t =>
                        {
                            t.HasTrigger("PriceAudit");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.ProductSuppliers.Audits.ProductSupplayerAudit", b =>
                {
                    b.Property<Guid>("AuditId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecovered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("AuditId");

                    b.ToTable("ProductSupplayerAudits");
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.ProductSuppliers.ProductSupplayer", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SupplayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("ProductId", "SupplayerId");

                    b.HasIndex("SupplayerId");

                    b.ToTable("ProductSupplayers", t =>
                        {
                            t.HasTrigger("ProductSupplayerAudit");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.Products.Audits.ProductAudit", b =>
                {
                    b.Property<Guid>("AuditId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CatagoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CountryOfOriginId")
                        .HasColumnType("int");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAllowedOnline")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecovered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MainTax")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProductGroupId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiptType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SubTax")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("TotalTaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("AuditId");

                    b.ToTable("ProductAudits");
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CatagoryId")
                        .HasColumnType("int");

                    b.Property<int>("CountryOfOriginId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsAllowedOnline")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MainTax")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProductGroupId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiptType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SubTax")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("TotalTaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CatagoryId");

                    b.HasIndex("CountryOfOriginId");

                    b.HasIndex("ProductGroupId");

                    b.ToTable("Products", t =>
                        {
                            t.HasTrigger("ProductAudit");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.Suppliers.Audits.SupplayerAudit", b =>
                {
                    b.Property<Guid>("AuditId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecovered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("AuditId");

                    b.ToTable("SupplayerAudits");
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.Suppliers.Supplayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Supplayers", t =>
                        {
                            t.HasTrigger("SupplayerAudit")
                                .HasDatabaseName("SupplayerAudit1");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.Availablty.Audits.AvailabltyAudit", b =>
                {
                    b.OwnsOne("Smraa_AlYaman.Domain.Availablty.Audits.AvailabltyEntityId", "EntityId", b1 =>
                        {
                            b1.Property<Guid>("AvailabltyAuditAuditId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("BranchId")
                                .HasColumnType("int")
                                .HasColumnName("BranchId");

                            b1.Property<int>("ProductId")
                                .HasColumnType("int")
                                .HasColumnName("ProductId");

                            b1.HasKey("AvailabltyAuditAuditId");

                            b1.ToTable("AvailabltyAudits");

                            b1.WithOwner()
                                .HasForeignKey("AvailabltyAuditAuditId");
                        });

                    b.Navigation("EntityId")
                        .IsRequired();
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.Availablty.ProductBranchesAvailability", b =>
                {
                    b.HasOne("Smraa_AlYaman.Domain.Branchs.Branch", null)
                        .WithMany("ProductAvailabilities")
                        .HasForeignKey("BranchId");

                    b.HasOne("Smraa_AlYaman.Domain.Products.Product", null)
                        .WithMany("BranchesAvailability")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.Barcodes.Barcode", b =>
                {
                    b.HasOne("Smraa_AlYaman.Domain.Products.Product", "Product")
                        .WithMany("Barcodes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.CustomPrices.Audits.CustomPriceAudit", b =>
                {
                    b.OwnsOne("Smraa_AlYaman.Domain.CustomPrices.Audits.CustomPriceId", "EntityId", b1 =>
                        {
                            b1.Property<Guid>("CustomPriceAuditAuditId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Barcode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Barcode");

                            b1.Property<int>("BranchId")
                                .HasColumnType("int")
                                .HasColumnName("BranchId");

                            b1.HasKey("CustomPriceAuditAuditId");

                            b1.ToTable("CustomPriceAudits");

                            b1.WithOwner()
                                .HasForeignKey("CustomPriceAuditAuditId");
                        });

                    b.Navigation("EntityId")
                        .IsRequired();
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.CustomPrices.CustomPrice", b =>
                {
                    b.HasOne("Smraa_AlYaman.Domain.Branchs.Branch", "Branch")
                        .WithMany("CustomPrices")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Smraa_AlYaman.Domain.Barcodes.Barcode", "Barcode")
                        .WithMany("Prices")
                        .HasForeignKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barcode");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.OrderItems.OrderItem", b =>
                {
                    b.HasOne("Smraa_AlYaman.Domain.Barcodes.Barcode", "BarcodeNavigation")
                        .WithMany()
                        .HasForeignKey("BarcodeNavigationCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Smraa_AlYaman.Domain.Orderes.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BarcodeNavigation");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.ProductPrices.ProductPrice", b =>
                {
                    b.HasOne("Smraa_AlYaman.Domain.Products.Product", "Product")
                        .WithOne("ProductPrice")
                        .HasForeignKey("Smraa_AlYaman.Domain.ProductPrices.ProductPrice", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.ProductSuppliers.Audits.ProductSupplayerAudit", b =>
                {
                    b.OwnsOne("Smraa_AlYaman.Domain.ProductSuppliers.Audits.ProductSupplayerEntityId", "EntityId", b1 =>
                        {
                            b1.Property<Guid>("ProductSupplayerAuditAuditId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("ProductId")
                                .HasColumnType("int")
                                .HasColumnName("ProductId");

                            b1.Property<int>("SupplayerId")
                                .HasColumnType("int")
                                .HasColumnName("SupplayerId");

                            b1.HasKey("ProductSupplayerAuditAuditId");

                            b1.ToTable("ProductSupplayerAudits");

                            b1.WithOwner()
                                .HasForeignKey("ProductSupplayerAuditAuditId");
                        });

                    b.Navigation("EntityId")
                        .IsRequired();
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.ProductSuppliers.ProductSupplayer", b =>
                {
                    b.HasOne("Smraa_AlYaman.Domain.Products.Product", "Product")
                        .WithMany("ProductSupplayers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Smraa_AlYaman.Domain.Suppliers.Supplayer", "Supplayer")
                        .WithMany("ProductSuppliers")
                        .HasForeignKey("SupplayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Supplayer");
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.Products.Product", b =>
                {
                    b.HasOne("Smraa_AlYaman.Domain.CatagoryGroupAndBrand.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Smraa_AlYaman.Domain.CatagoryGroupAndBrand.Catagory", "Catagory")
                        .WithMany()
                        .HasForeignKey("CatagoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Smraa_AlYaman.Domain.CatagoryGroupAndBrand.CountryOfOrigin", "CountryOfOrigin")
                        .WithMany()
                        .HasForeignKey("CountryOfOriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Smraa_AlYaman.Domain.CatagoryGroupAndBrand.Group", "ProductGroup")
                        .WithMany()
                        .HasForeignKey("ProductGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Catagory");

                    b.Navigation("CountryOfOrigin");

                    b.Navigation("ProductGroup");
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.Barcodes.Barcode", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.Branchs.Branch", b =>
                {
                    b.Navigation("CustomPrices");

                    b.Navigation("ProductAvailabilities");
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.Orderes.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.Products.Product", b =>
                {
                    b.Navigation("Barcodes");

                    b.Navigation("BranchesAvailability");

                    b.Navigation("ProductPrice")
                        .IsRequired();

                    b.Navigation("ProductSupplayers");
                });

            modelBuilder.Entity("Smraa_AlYaman.Domain.Suppliers.Supplayer", b =>
                {
                    b.Navigation("ProductSuppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
